In [11]:
###Numpy
l1 = [1,2,3,4,5]
import numpy as np
### define a 1-D array in numpy

arr1 = np.array(l1)
arr2 = np.array([1,2,3,4,5])
# print(arr1)
# print(arr2)

## define 2-D array
# l1 = [1,2,3]
# l11 = [4,5,6]
# l2 = [l1,l11]
# print(type(l2[1]))
# arr2 = np.array(l2)

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)


# define 3-D array
l3 = [[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]
arr3 = np.array(l3)






[[1 2 3]
 [4 5 6]]


In [30]:

import numpy as np 
arr1 = np.array([1,  2,  3,  4,  5])
#                0,  1,  2,  3   4
#                -5, -4,-3, -2, -1
arr2 = np.array([[1,2,3],[4,5,6]])
l3 = [[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]
arr3 = np.array(l3)
### shape of an array
# print(np.shape(arr3))
### check number of dim
# print(arr2.ndim)
# print(arr3)

### access the elements of a 1-D array
# print(arr1[0])
# print(arr1[4])
# print(arr1[-1])
# print(arr1[2]+arr1[3])

### access the elements of a 2-D array
arr2 = np.array([[1,2,3],[4,5,6]])
# print(arr2[1,2])


### access the elements of a 3-D array
l3 = [[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]
arr3 = np.array(l3)  #0,1,1
arr3[0,-1,-2] 
# arr3[0,1,1] the same result



 



2


5

In [42]:
### slice an array
import numpy as np
arr = np.array([1,2,3,4,5,6,7])

# print(arr[1:5])
# print(arr[4:]) # 4th element until final element
# print(arr[:4])
# print(arr[1:5:2])
print(arr[::2])

arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr1[1,1:4])
print(np.shape(arr1))
print(arr1.ndim)


[1 3 5 7]
[7 8 9]
(2, 5)
2


In [24]:
##  define 1*5 array and 5*1 array
a11 = np.array([[1,2,3,4,5]])
a1 = np.array([[1],[2],[3],[4],[5]])
print(np.shape(a11))
print(np.shape(a1))

(1, 5)
(5, 1)


In [46]:
### call by value and call by ref in numpy array
arr1 = np.array([[1,2,3,4,5]])
arr2 = np.array(arr1)  # arr2 = arr1.copy()
arr3 = np.asarray(arr1) # occupies the same memory arr1.view()
arr1[0,0] = 0
print(arr1)
print(arr2)
print(arr3)


[[0 2 3 4 5]]
[[1 2 3 4 5]]
[[0 2 3 4 5]]
